#!/bin/bash

set -e

swift build

export DYLD_LIBRARY_PATH=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/lib/swift/macosx

.build/debug/Tests/FileSystem/Directory
.build/debug/Tests/FileSystem/File
.build/debug/Tests/FileSystem/FileLogger
.build/debug/Tests/FileSystem/Path
